{% set name = "earthkit-data" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ca6d737f5ba09e958424ec3eb5c2c801b726d3ea582a017a2f38c99b97eeb71a

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.8
    - pip
    - pytest-runner
  run:
    - cfgrib >=0.9.10.1
    - dask
    - eccodes >=2.34.1
    - entrypoints
    - filelock
    - jinja2
    - netcdf4
    - pandas
    - pdbufr
    - python >=3.8
    - python-eccodes >=1.7.0
    - pyyaml
    - requests
    - tqdm
    - xarray

test:
  imports:
    - earthkit.data

about:
  home: https://github.com/ecmwf/earthkit-data
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A format-agnostic interface for geospatial data with a focus on meteorology and climate science.
  doc_url: https://earthkit-data.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/earthkit-data

extra:
  recipe-maintainers:
    - sandorkertesz
    - iainrussell
    - JamesVarndell
