{% set name = "earthkit-data" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c65944a65b0978c8c0ec485721bc03df561551f9401f81d3605a4e4e13200a5

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.8
    - pip
    - pytest-runner
  run:
    - cfgrib >=0.9.10.1
    - dask
    - entrypoints
    - filelock
    - jinja2
    - netcdf4
    - pandas
    - pdbufr
    - python >=3.8
    - python-eccodes
    - pyyaml
    - requests
    - tqdm
    - xarray

test:
  imports:
    - earthkit.data

about:
  home: https://github.com/ecmwf/earthkit-data
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A format-agnostic interface for geospatial data with a focus on meteorology and climate science.
  doc_url: https://earthkit-data.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/earthkit-data

extra:
  recipe-maintainers:
    - sandorkertesz
    - iainrussell
    - JamesVarndell
