{% set name = "earthkit-data" %}
{% set version = "0.16.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b2d8e555648f43685710a939885a25b41f611844db4da140ce57bcbddca09e8f

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
  run:
    - array-api-compat
    - cfgrib >=0.9.10.1
    - dask
    - deprecation
    - earthkit-geo >=0.2
    - earthkit-utils
    - eccodes >=2.35.0
    - entrypoints
    - filelock
    - jinja2
    - jsonschema
    - lru-dict
    - markdown
    - multiurl
    - netcdf4
    - pandas
    - pdbufr >=0.11
    - python >={{ python_min }}
    - python-eccodes >=1.7.0
    - pyyaml
    - requests
    - tqdm >=4.63
    - xarray >=0.19

test:
  requires:
    - python {{ python_min }}
  imports:
    - earthkit.data

about:
  home: https://github.com/ecmwf/earthkit-data
  license: Apache-2.0
  license_family: Apache
  license_file: LICENCE
  summary: A format-agnostic interface for geospatial data with a focus on meteorology and climate science.
  doc_url: https://earthkit-data.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/earthkit-data

extra:
  recipe-maintainers:
    - sandorkertesz
    - iainrussell
    - JamesVarndell
